# Generated by Django 4.1.7 on 2023-03-23 16:37

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(help_text='30 karakter veya daha az, Türkçe olmayan, harf ve rakamlardan bir kelime.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Kullanıcı Adı')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta')),
                ('is_active', models.BooleanField(default=True, help_text='Bu kullanıcının etkin olarak işlem görüp görmediğini belirler. Hesapları silmek yerine bunun işaretini kaldırın.', verbose_name='Kullanıcı etkin mi ?')),
                ('user_permission', models.CharField(choices=[('superuser', 'Süper Yönetici'), ('manager', 'Yönetici'), ('member', 'Normal Üye')], default='member', help_text='Kullanıcının sitedeki erişim sınırını belirler.', max_length=20, verbose_name='Kullanıcı Yetki')),
                ('last_login', models.DateTimeField(blank=True, help_text='Kullanıcının en son sistemde oturum açma tarihi.', null=True, verbose_name='Son Oturum Açma')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Kullanıcının sisteme kayıt tarihi.', verbose_name='Kayıt Tarihi')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'users',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserPasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.CharField(max_length=120, verbose_name='Parola Sıfırlama Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_code', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Parola Kodu',
                'verbose_name_plural': 'Parola Kodları',
                'db_table': 'user_password_reset_codes',
                'ordering': ['-id'],
            },
        ),
    ]
